PROG=sink

CFLAGS+= -I/usr/local/include -g -O
LDFLAGS+= -L/usr/local/lib  -g
LDFLAGS+= -L/usr/local/lib/event2 -levent
#/usr/local/lib/event2/libevent.a 
#-levent2 

NO_MAN=1

.include <bsd.prog.mk>
